### ISSUE TITLE
Class Completion Items

### ISSUE THREAD

**Issue by daniglas** [prominic/groovy-language-server#11]
Hey! Just wondering if it is possible to enable class(probably a better way to say this) completion items. 

For instance, in IntelliJ, when I start typing A-r-r-a-y-L... I get suggestions for "ArrayList". It seems as if this language server is only showing completion suggestions when the trigger character is pressed.

Thanks for any input!

**Comment by joshtynjala** [comment]
Not possible at the moment, but I'll look into it!

**Comment by daniglas** [comment]
Out of curiosity, how would you go about implementing it?

**Comment by joshtynjala** [comment]
I should be able to figure out if the AST node at the current offset isn't some kind of expression, like member access accessing a field or method. In other words, something like the body of a method. In that case, it should be safe to include all classes in the completion result. I'm already storing a list of all classes that have been encountered in the AST, so it's easy to iterate over them all and convert to completion items.

**Comment by daniglas** [comment]
Gotcha.

As far as classes encountered in the AST, would that included for instance java standard library classes(ex: java.util.*)?

**Comment by joshtynjala** [comment]
I might not have those classes stored anywhere right now, but I certainly intend to include them in completion.

**Comment by daniglas** [comment]
How would you go about getting the classes in those libraries? Also, if the user adds to the classpath, how would one go about getting those classes?

**Comment by daniglas** [comment]
Nevermind! Figured it out

**Comment by joshtynjala** [comment]
After today's commits, classes will appear in the completion list in a number of places, including built-in classes in the java.* package.
