### ISSUE TITLE
Cannot run vscode extension any more

### ISSUE THREAD

**Issue by lhein** [prominic/groovy-language-server#15]
When trying to launch the vscode extension from sources(master branch) it fails with the following errors:

https://gist.github.com/lhein/83ba947c57d409af467f62af9e5b1907

VSCode version: 1.40.0
Electron: 6.1.2
Node: 12.4.0

**Comment by lhein** [comment]
figured out that it lacks files in the build folder. I think you should be able to see the same issue when renaming the build folder locally and re-run the gradle build.

**Comment by joshtynjala** [comment]
Unfortunately, I could not reproduce by deleting the _build_ folder. Try deleting the _node_modules_ folder before building.

**Comment by lhein** [comment]
I tried that and it simply does not populate the build folder.

build
build/bin
build/bin/groovy-language-server-all.jar
build/groovy-0.0.0.vsix
build/package.json

is all I have in that folder which isn't enough.

**Comment by lhein** [comment]
Is that by any chance an OS related issue? Have you got a Linux box where you could test it too?

**Comment by joshtynjala** [comment]
I'm not sure what exactly I did, but I can now reproduce this issue.

**Comment by lhein** [comment]
That is progress :) So it should be easier to track now.

**Comment by joshtynjala** [comment]
I was trying to run two separate commands in a single Exec task, which caused the second one to overwrite the first. I've now separated them into two tasks, and I confirm that they're both running.

**Comment by lhein** [comment]
Thanks, I will try this soon.

**Comment by lhein** [comment]
Works perfectly! Great!
