### ISSUE TITLE
unable to resolve base groovy classes

### ISSUE THREAD

**Issue by aconchillo** [prominic/groovy-language-server#17]
The server is unable to resolve base groovy classes or annotations, but it is able to resolve grapes which have been installed in `~/.groovy/grapes`.

I'm using groovy from homebrew `brew install groovy` which installs groovy in `/usr/local/Cellar/groovy/2.5.8`. I have tried to set `GROOVY_HOME` without success.

For example:

```
@Grapes([
        @Grab('mysql:mysql-connector-java:8.0.11'),
        @Grab('joda-time:joda-time:2.10'),
        @Grab('org.slf4j:slf4j-api:1.7.25'),
        @Grab('ch.qos.logback:logback-classic:1.2.3'),
    @Grab('org.mongodb:mongodb-driver:3.7.1'),
    @Grab('org.mongodb:bson:3.8.0'),
    @Grab('javax.xml.bind:jaxb-api:2.2.3'),
    @Grab('org.apache.commons:commons-lang3:3.7'),
    @Grab('com.mashape.unirest:unirest-java:1.4.9'),
    @GrabConfig(systemClassLoader = true)
])

....

import groovy.transform.Field
```

I get:

```
unable to resolve class groovy.sql.Sql
 @ line 1, column 1.

unable to resolve class Grapes ,  unable to find class for annotation
 @ line 1, column 1.

unable to resolve class Grapes ,  unable to find class for annotation
 @ line 1, column 1.
```

and

```
unable to resolve class groovy.transform.Field
 @ line 17, column 1.
```

**Comment by dansomething** [comment]
The Groovy language server needs to be configured with a list of paths that can either be to a `.jar` file or a directory containing `.jar` files.

See here:
https://github.com/prominic/groovy-language-server/blob/master/src/main/java/net/prominic/groovyls/GroovyServices.java#L179
and here:
https://github.com/prominic/groovy-language-server/blob/master/src/main/java/net/prominic/groovyls/config/CompilationUnitFactory.java#L116

Here's an example configuring the language server from [coc.nvim](https://github.com/neoclide/coc.nvim/wiki/Language-servers#groovy). I believe project relative paths will also work.
```json
{
  "languageserver": {
    "groovy": {
      "trace.server": "off",
      "command": "java",
      "args": [
        "-jar",
        "/path/to/groovy-language-server/build/libs/groovy-language-server-all.jar"
      ],
      "filetypes": ["groovy"],
      "settings": {
        "groovy": {
          "classpath": [
            "/path/to/.groovy/grapes/org.codehaus.groovy/groovy-sql/jars/groovy-sql-3.0.1.jar",
            "/path/to/.groovy/grapes/org.codehaus.groovy/groovy/jars/groovy-3.0.1.jar",
            "/path/to/groovy/libs",
            "./libs"
          ]
        }
      }
    }
  }
}
```

**Comment by aconchillo** [comment]
I finally had time to figure out how to do this in Emacs with lsp-mode. I actually just added support for it:

https://github.com/emacs-lsp/lsp-mode/pull/2139

Closing.
