### ISSUE TITLE
groovy-language-server sh script points to wrong jar

### ISSUE THREAD

**Issue by joshzcold** [prominic/groovy-language-server#22]
This script points to groovy-language-server-all.jar
```sh
cat groovy-language-server 
#!/usr/bin/env bash

DIR=$(cd $(dirname $0); pwd)
java -jar $DIR/build/libs/groovy-language-server-all.jar

```
but executing `./gradlew clean build` produces
`groovy-language-server/build/libs/groovy-language-server.jar
`

**Comment by joshtynjala** [comment]
When you build with Gradle, groovy-language-server-all.jar is produced here:

groovy-language-server/build/libs/groovy-language-server-all.jar
