### ISSUE TITLE
How to combine groovy-language-server with monaco-editor

### ISSUE THREAD

**Issue by cxwSuperman** [prominic/groovy-language-server#32]
I look at the example using **vscode-json-languageservice,** and then I want to use **groovy-language-server**, but I failed to introduce it in the first step, please help me

**Comment by joshtynjala** [comment]
I'm afraid that I have no experience working with Monaco editor directly. I know that VSCode uses Monaco, but it's abstracted away, so I don't know anything about its APIs. I wish I could provide more advice!
