### ISSUE TITLE
Exposing groovy LSP on a socket

### ISSUE THREAD

**Issue by juangrases** [prominic/groovy-language-server#33]
I would like to integrate with CodeMirror using https://github.com/wylieconlon/lsp-editor-adapter but if I am understanding correctly I will need to make the LSP accessible through a socket port. Is this possible here? 

Thanks!

**Comment by joshtynjala** [comment]
There is currently no way to use the Groovy language server with any kind of socket, including web sockets. In the static main() method, you can see that it uses `System.in` and `System.out` for communication:

https://github.com/prominic/groovy-language-server/blob/6ffe912a964a37b944a2eaf9a76fa3ca7ef4fad5/src/main/java/net/prominic/groovyls/GroovyLanguageServer.java#L48

It wouldn't be too difficult to support regular TCP sockets too, but web sockets are their own special thing. That's not really something I want to burden everyone with when very few people will probably use web sockets.

I think that your best bet is to use the Groovy language server .jar file as a library, and create your own main() entry point to instantiate the `GroovyLanguageServer` class using `Launcher.createLauncher()` with whatever I/O streams are available for your web sockets.
