### ISSUE TITLE
how to use the groovy-language-server in monaco editor

### ISSUE THREAD

**Issue by tttmmiao** [prominic/groovy-language-server#34]
I need to integrate the groovy-language-server to monaco editor. 
For groovy, is there groovy language service extracted from VSCode to be reused in Monaco Editor? e.g., vscode-css-languageservice and vscode-json-languageservice.

**Comment by joshtynjala** [comment]
The Groovy language server is written in Java. I suspect that this will make it difficult to integrate with Monaco, unless you are using Electron or something else that allows you to start a Java process.
