### ISSUE TITLE
How to build without direct internet access?

### ISSUE THREAD

**Issue by kaddkaka** [prominic/groovy-language-server#42]
How can I get the the groovyls running on a computer without direct internet access? `./gradlew build` tried to download things from gradle.org which is not accessible.

```Downloading https://services.gradle.org/distributions/gradle-6.3-bin.zip```

I currently have `Gradle 4.4.1` installed.

What is the list of dependencies?

**Comment by joshtynjala** [comment]
The dependencies are specified in build.gradle.

https://github.com/prominic/groovy-language-server/blob/master/build.gradle

I guess that you'll need to install them manually?

**Comment by kaddkaka** [comment]
Right thanks. I already installed gradle 6.3 manually, but I still get the automatic download mentioned in the OP.

**Comment by Jaakkonen** [comment]
Java/groovy/JVM ecosystem dependencies work with packages found from Maven/Ivy/etc repositories. These are all defined using a build tool, in this projects case Gradle and in some other projects Maven or Groovy Grape. These load in the dependencies to a local repository when building. The .jar and other files in these packages are used to construct JVM classpath where all the depended things can be discovered by the runtime and compiler.

Here are some resources for getting Gradle to download dependencies before hand or on other machine and to do the build job without internet:
https://stackoverflow.com/questions/28436473/build-gradle-repository-for-offline-development
https://stackoverflow.com/questions/37733752/gradle-offline-how-to-cache-the-dependencies
(Note: [before gradle 6.1 the caches are not always relocatable](https://github.com/gradle/gradle/issues/1338#issuecomment-565691159) leading to dependencies being sometimes downloaded when existing caches are not found)

**Comment by joshtynjala** [comment]
Since it is Java, you should be able to build the project on another computer and then transfer the .jar file to another computer. I cannot provide any further advice for building on a computer without internet access.
