### ISSUE TITLE
Split vscode extention to its own repo

### ISSUE THREAD

**Issue by shadycuz** [prominic/groovy-language-server#48]
I'm somewhat active in the Jenkins community and stay up to date on what's available in the tooling ecosystem, especially when it comes to groovy. I have been wanting some IDE groovy help for a while and a few days ago started looking at the LSP protocol and extension guides for vscode. Through my googling I came across this repo which eventually I realized contained a extension for vscode that works pretty good.

I guess my real complaint is how hard it is to find  the extension and install the extension etc. I was thinking I could just fork the code and then strip everything but the extension, improve somethings and list it in vscode plugin marketplace but as a [maintainer](https://github.com/DontShaveTheYak/) myself that just felt disingenuous. 

So I thought I would just ask you what are your plans are for the extension? Maybe you have actually been waiting for someone to come along and take ownership of it. Maybe you are planning things for it. I'm just waiting to help others by improving their productivity in groovy. 

Thanks,
Levi

**Comment by joshtynjala** [comment]
> So I thought I would just ask you what are your plans are for the extension?

We have no plans to release the VSCode extension to the Marketplace or to expand it with any new features. This repo is primarily focused on a language server, and we actually created the language server for a different editor (Moonshine) that also supports the language server protocol. The VSCode extension in this repo exists so that I can verify that the language server works in both VSCode and Moonshine, and to show how someone might get started creating a real VSCode extension. If you want to create a full-featured extension, go for it! I'll be happy to add a link to your project's page on the Marketplace, once you get things going.

**Comment by shadycuz** [comment]
I finally got some free time https://github.com/DontShaveTheYak/groovy-butler, you probably seen my embarassing PR fiasco #49. 

I think my next step is to figure out how to get the language server running when the extension is activated in a workspace? So yeah wish me luck lol. I'm thinking docker if I can find a working example somewhere.

**Comment by shadycuz** [comment]
So I thought I was going to use docker because I assumed server meant TCP communication, but it appears its stdin and out. I'm really struggling to understand how to get the server down onto the machine other than maybe building the jar and the hosting it my self and then curling it down? 🤔

**Comment by shadycuz** [comment]
Hmmm the best plan I can think of is adding your repo to my project as a submodule. Then in my CICD replacing your `build.gradle` with my own version so I can publish to my github packages so I can have a place to curl down the server jar file 🤔.

**Comment by shadycuz** [comment]
Got packages [working](https://github.com/DontShaveTheYak/groovy-butler/packages/882163) but that was a waste of time, turns out you cant download them without credentials even though they are public in a puiblic repo. 

Going to try release assets next.

**Comment by shadycuz** [comment]
Release assets work better and was the obvious choice that I somehow overlooked. 

This whole fork/pr redirection is killing me. I looked up how to make it stop and apprently I need to delete my repo and then recreate it and mirror the history. Since I wanted to change the name from `groovy-butler` to `groovy-guru` I did just that. 

New repo is here https://github.com/DontShaveTheYak/groovy-guru

I need to read up on the extension API and LSP. That way I can improve the extension but also contribute back to `groovy-language-server`.

**Comment by shadycuz** [comment]
And it's live https://marketplace.visualstudio.com/items?itemName=DontShaveTheYak.groovy-guru 🎉 

@joshtynjala Do you mind if I reply to the issues for vscode features, like `#18` and encourage them to move the issue to the [stand alone plugin repo](https://github.com/DontShaveTheYak/groovy-guru)?

**Comment by joshtynjala** [comment]
> Do you mind if I reply to the issues for vscode features, like #18 and encourage them to move the issue to the stand alone plugin repo?

@shadycuz Yeah, go ahead.
