### ISSUE TITLE
Primary Typing support, 

### ISSUE THREAD

**Issue by frett27** [prominic/groovy-language-server#5]
Hi, 
I needed to support the static typed of groovy, to be able to have autocomplete
here are the modifications made on the software, this can probably help to see what's used and how has been solved in my case, certainly you may have a more convenient solution aligned with your project ?

[typing_static.zip](https://github.com/prominic/groovy-language-server/files/3513436/typing_static.zip)

in my case, the use was inlined with a software, 
the fist modification is to change the compilation phase to Phases.INSTRUCTION_SELECTION (the inferred types are only available in this phase), this is also more slower but more relevant.

the second modification is to use the associated metadataclass info in groovyastutil

```java
   } else if (var.isDynamicTyped()) {
            	
            	// If Static Type exists, use it
            	if (node.getMetaDataMap() != null) {
	            	Object inferred = node.getMetaDataMap().get(StaticTypesMarker.INFERRED_TYPE);
	            	if (inferred != null) {
	            		return (ClassNode)inferred;
	            	}
            	}
            	// END
```

hope to read you 

Patrice

**Comment by joshtynjala** [comment]
@frett27 Can you share a simple example of some Groovy code that doesn't properly resolve types currently, but it works correctly with your patch? Thank you!
